
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scsslint:
    enabled: true

ratings:
  paths:
  #- app/**
  - "**.php"
  - "**.js"
  - "**.css"
  - "**.scss"

exclude_paths:
- fonts/*
- css/foundation.css
- r8conf2016/css/foundation.css
- tests/**/*
- spec/**/*
- ng/**/*
- js/d3/*
- js/d3plus/*
- js/foundation/*
- js/guillotine/*
- js/tinymce/*
- js/vendor/*
- r8conf2016/js/vendor/*
- js/**/vis.js
- phpmailer/*
- js/jquery.fancybox.js
- r8conf2016/js/jquery.fancybox.js
- "**.min.css"
- "**.min.js"
