
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: false
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  scsslint:
    enabled: true

ratings:
  paths:
  #- app/**
  - "**.php"
  - "**.js"
  - "**.css"
  - "**.scss"

exclude_paths:
- fonts/*
- tests/**/*
- spec/**/*
- js/d3/*
- js/d3plus/*
- js/foundation/*
- js/guillotine/*
- js/tinymce/*
- js/vendor/*
- js/vis.js/*
- phpmailer/*
